"""Add embedded_images and storage_type columns to posts table

Revision ID: 7be337f2ef03
Revises: c8121b36d9fc
Create Date: 2025-07-02 16:56:41.104811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be337f2ef03'
down_revision = 'c8121b36d9fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('embedded_images', sa.Text(), nullable=True, comment='임베딩된 이미지 URL 목록 (JSON)'))
    op.add_column('posts', sa.Column('storage_type', sa.String(), nullable=False, server_default='local', comment='저장소 타입 (local, s3)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'storage_type')
    op.drop_column('posts', 'embedded_images')
    # ### end Alembic commands ###
